-- Create supervisor_bonuses table for syncing bonus records
CREATE TABLE IF NOT EXISTS supervisor_bonuses (
  id VARCHAR(100) PRIMARY KEY,
  client_id VARCHAR(36) NOT NULL,
  branch_id VARCHAR(36),
  supervisor_id VARCHAR(36) NOT NULL,
  supervisor_name VARCHAR(255) DEFAULT '',
  period_start VARCHAR(20) DEFAULT '',
  period_end VARCHAR(20) DEFAULT '',
  total_team_sales DECIMAL(15,2) DEFAULT 0,
  bonus_percentage DECIMAL(5,2) DEFAULT 0,
  bonus_amount DECIMAL(15,2) DEFAULT 0,
  manual_bonus_amount DECIMAL(15,2) DEFAULT NULL,
  total_deposits DECIMAL(15,2) DEFAULT NULL,
  user_id VARCHAR(36) DEFAULT '',
  user_name VARCHAR(255) DEFAULT '',
  notes TEXT DEFAULT NULL,
  sales_reps JSON DEFAULT NULL,
  invoice_ids JSON DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  server_updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  sync_version INT DEFAULT 1,
  is_deleted BOOLEAN DEFAULT FALSE,
  INDEX idx_supervisor_bonuses_client (client_id),
  INDEX idx_supervisor_bonuses_supervisor (supervisor_id),
  INDEX idx_supervisor_bonuses_period (period_start, period_end),
  INDEX idx_supervisor_bonuses_created (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
